<a href="https://colab.research.google.com/github/KC-7/learn-pytorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions RE Notebook Can Be Asked Here: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


print(torch.__version__)

2.1.0+cu121


## Introduction to Tensors
### Creating Tensors

PyTorch Tensors are created using `torch.Tensor()` - https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int

scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# TENSOR - Test 2
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9],
                        [10, 11, 12],
                        [13, 14, 15],
                        [16, 17, 18]]])

TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 6, 3])

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])

### Random Tensors

Why random tensors?

Random tensors are important because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at data -> Update random numbers -> Look at data -> Update random numbers`

https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)

random_tensor

tensor([[0.2552, 0.8569, 0.6022, 0.4888],
        [0.6781, 0.0628, 0.1787, 0.0683],
        [0.9632, 0.2965, 0.1436, 0.7717]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
random_tensor[0]

tensor([0.2552, 0.8569, 0.6022, 0.4888])

In [ ]:
# Create a random tensor of size 10, 10, 10)
random_tensor2 = torch.rand(10, 10, 10)

random_tensor2

tensor([[[5.3236e-02, 6.1356e-01, 8.1858e-01, 7.0635e-01, 3.6923e-02,
          6.0206e-01, 1.5470e-01, 6.5929e-01, 8.8378e-01, 1.2031e-01],
         [5.5054e-01, 3.2921e-02, 5.6263e-01, 3.0068e-01, 5.5789e-02,
          3.1418e-01, 7.8502e-01, 8.0191e-01, 4.8388e-01, 6.4416e-02],
         [8.8860e-01, 5.2882e-01, 9.0492e-01, 2.2150e-03, 9.9254e-01,
          4.5803e-01, 7.0228e-01, 7.5480e-01, 3.9310e-01, 6.9023e-01],
         [2.3257e-03, 1.1428e-01, 2.5602e-01, 4.2623e-01, 4.1698e-01,
          4.6947e-01, 4.5090e-01, 9.1669e-01, 7.8724e-02, 5.1126e-01],
         [8.7170e-01, 2.3652e-01, 4.7191e-01, 4.1310e-01, 4.5251e-01,
          7.4971e-01, 6.9726e-01, 3.9081e-01, 4.1109e-01, 3.6908e-01],
         [9.6780e-01, 9.7909e-02, 5.8009e-01, 6.0670e-01, 6.1343e-01,
          8.9664e-01, 1.7941e-01, 3.0309e-01, 9.4788e-03, 3.3488e-01],
         [7.2110e-01, 2.8443e-01, 8.1318e-01, 9.9807e-01, 2.1697e-02,
          9.0236e-01, 7.8770e-01, 5.9006e-01, 8.7781e-01, 5.6636e-02],
         [6.9

In [ ]:
random_tensor2.ndim

3

In [ ]:
random_tensor2.shape

torch.Size([10, 10, 10])

In [ ]:
random_tensor2.dtype

torch.float32

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channels (R, G, B), height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros & Ones


In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))

zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))

ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

Documentation: https://pytorch.org/docs/stable/generated/torch.arange.html

In [ ]:
# Use torch.arange()
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Use torch.arange() with step
arrange_example = torch.arange(start=0, end=1000, step=77)
arrange_example

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
# Creating tensors like

ten_zeros = torch.zeros_like(input=one_to_ten)
one_to_ten, ten_zeros

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]))

In [ ]:
# Creating tensors like - example 2

image_size_zeros_tensor = torch.zeros_like(input=random_image_size_tensor)
random_image_size_tensor, image_size_zeros_tensor

(tensor([[[0.3968, 0.5293, 0.4624,  ..., 0.7730, 0.5149, 0.6485],
          [0.2646, 0.8114, 0.3970,  ..., 0.2501, 0.7599, 0.4473],
          [0.8295, 0.3131, 0.2725,  ..., 0.8885, 0.1161, 0.2942],
          ...,
          [0.4027, 0.1440, 0.3965,  ..., 0.5026, 0.4072, 0.3234],
          [0.5591, 0.2465, 0.0689,  ..., 0.9213, 0.6885, 0.7867],
          [0.4022, 0.5523, 0.7707,  ..., 0.0931, 0.0137, 0.2451]],
 
         [[0.4761, 0.9813, 0.5542,  ..., 0.0788, 0.1337, 0.5291],
          [0.9127, 0.7382, 0.1196,  ..., 0.6513, 0.0036, 0.5265],
          [0.9586, 0.7108, 0.3922,  ..., 0.3105, 0.3104, 0.3456],
          ...,
          [0.4604, 0.5994, 0.0798,  ..., 0.9912, 0.7971, 0.7559],
          [0.9736, 0.7668, 0.9655,  ..., 0.8411, 0.6480, 0.1932],
          [0.4445, 0.2233, 0.9157,  ..., 0.2474, 0.2136, 0.9622]],
 
         [[0.4368, 0.4308, 0.5634,  ..., 0.9225, 0.2415, 0.1970],
          [0.9093, 0.9946, 0.8010,  ..., 0.2340, 0.6789, 0.8115],
          [0.8416, 0.2916, 0.0530,  ...,

### Tensor Datatypes

**Documentation & Resources:**
- https://pytorch.org/docs/stable/tensors.html
- https://en.wikipedia.org/wiki/Precision_(computer_science)

**Notes:**
- float32 is the default datatype (32bits)
- float16 is faster for numbers that take up less memory (16bits)
- float64 is used for more detail in memory (64bits)
- **Tensor datatypes is one of the 3 main errors you will encounter when using Pytorch & Deep Learning: 1) Tensors not right datatype, 2) Tensors not right shape, 3) Tensors not right device.**

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor? (Eg: "float32" or "float16")
                               device=None, # What device is your tensor on? (Eg: "cuda", "cpu")
                               requires_grad=False) # Whether or not to track gradients with the tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Float 16 tensor - using the same data from the above float32 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
# Float 64 tensor
float_64_tensor = torch.tensor([2.0, 4.0, 6.0, 8.0],
                               dtype=torch.float64, # What datatype is the tensor? (Eg: "float32" or "float16")
                               device=None, # What device is your tensor on? (Eg: "cuda", "cpu")
                               requires_grad=False) # Whether or not to track gradients with the tensors operations
float_64_tensor

tensor([2., 4., 6., 8.], dtype=torch.float64)

In [ ]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

### Getting information from tensors (Tensor Attributes)

**3 Main Pytorch & Deep Learning Errors You May Encounter:**
1. Tensors not right datatype - to get the datatype from a tensor, use `tensor.dtype`
2. Tensors not right shape - to get the shape from a tensor, use `tensor.shape`
3. Tensors not right device - to get the device from a tensor, use `tensor.device`


In [ ]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1451, 0.3474, 0.7833, 0.2605],
        [0.9117, 0.8394, 0.3508, 0.0428],
        [0.5593, 0.1974, 0.3090, 0.3175]])

In [ ]:
# Find out details about some_tensor
print("Tensor: ", some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}") # float32 is default
print(f"Shape of tensor: {some_tensor.shape}") # tensor was created using torch.rand(3, 4)
print(f"Device tensor is on: {some_tensor.device}") # cpu is the default device

Tensor:  tensor([[0.1451, 0.3474, 0.7833, 0.2605],
        [0.9117, 0.8394, 0.3508, 0.0428],
        [0.5593, 0.1974, 0.3090, 0.3175]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [ ]:
# Create test_tensor
test_tensor = torch.rand((3, 4),
                               dtype=torch.float64, # What datatype is the tensor? (Eg: torch.float32 or torch.float16)
                               device='cpu', # What device is your tensor on? (Eg: "cuda", "cpu")
                               requires_grad=False) # Whether or not to track gradients with the tensors operations

# Find out details about test_tensor

print("Tensor: ", test_tensor)
print(f"Datatype of tensor: {test_tensor.dtype}") # tensor was created using float64 datatype
print(f"Shape of tensor: {test_tensor.shape}") # tensor was created using torch.rand(3, 4)
print(f"Device tensor is on: {test_tensor.device}") # tensor set to run on cpu

Tensor:  tensor([[0.3281, 0.9698, 0.2358, 0.1994],
        [0.0513, 0.6078, 0.1983, 0.4325],
        [0.3789, 0.0382, 0.3223, 0.2850]], dtype=torch.float64)
Datatype of tensor: torch.float64
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor123 = torch.tensor([1, 2, 3])
tensor123 + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor123 * 10

tensor([10, 20, 30])

In [ ]:
# Subtract 10 from tensor
tensor123 - 10

tensor([-9, -8, -7])

In [ ]:
# Try out PyTorch in-built Functions (NOTE: Use standard python as above where possible)
torch.mul(tensor123, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor123, 10)

tensor([11, 12, 13])

### Matrix Multiplication (VS Element Wise Multiplication)

**There are two main ways of preforming multiplication in neural networks and deep learning:**
1. Element-wise Multiplication
2. Matrix Multiplication (Dot Product)

Resources:
- https://www.mathsisfun.com/algebra/matrix-multiplying.html
- http://matrixmultiplication.xyz/

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` - This won't work
* `(2, 3) @ (3, 2)` - This will work
* `(3, 2) @ (2, 3)` - This will work
* You can test this by replacing the following numbers and testing the code: `torch.matmul(torch.random(3, 2), torch.random(3, 2)`
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
# Element Wise Multiplication
print(tensor123, "*", tensor123)
print(f"Equals: {tensor123 * tensor123}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# Matrix Multiplication
torch.matmul(tensor123, tensor123)

tensor(14)

In [ ]:
# Matrix Multiplication By Hand - Example 1
1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
# Matrix Multiplication By Hand - Example 2

%%time
value = 0
for i in range(len(tensor123)):
  value += tensor123[i] * tensor123[i]
print(value)

tensor(14)
CPU times: user 2.15 ms, sys: 58 µs, total: 2.21 ms
Wall time: 4.72 ms


In [ ]:
# Test Time for PyTorch matmul to demonstrate how much faster it is

%%time
torch.matmul(tensor123, tensor123)

CPU times: user 90 µs, sys: 13 µs, total: 103 µs
Wall time: 109 µs


tensor(14)

### One of the most common errors in deep learning is: shape errors



In [ ]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm is the same as torch.matmul, it's an alias for writing less code
torch.mm(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# Check shape of tensors (as the above code does not work and gets an error)
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix the shape issues, we can manipulate the shape of one of the tensors using a **transpose**.

A **transpose** switches the axis or dimensions of a given tensor.

In [ ]:
# Original Tensor B & Shape
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
# Transpose Tensor B & Display Updated Shape
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# Use Tranpose to resolve the matmul shape error
print(f"Original Shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New Shapes: tensor_A = {tensor_A.shape}, tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("\nOutput:")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput Shape: {output.shape}")


Original Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New Shapes: tensor_A = torch.Size([3, 2]), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match

Output:
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output Shape: torch.Size([3, 3])


In [ ]:
# Check Shape
torch.mm(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

## Finding  the min, max, mean, sum, etc (tensor aggregation)



In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10) # start, end, step
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean (Example with the datatype runtime error)
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
# Solution for above dtype error

# Check the datatype for x
x.dtype

torch.int64

In [ ]:
# The datatype is int64. The datatype error states the dtype be floating point or complex. Got: Long.

# Convert the dtype to float32 to resolve the dtype error
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max



In [ ]:
# Create a tensor
x1 = torch.arange(1, 101, 10) # start, end, step
x1

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimimum value occurs
x1.argmin()

tensor(0)

In [ ]:
x1[0]

tensor(1)

In [ ]:
# Find the position in tensor that has the maximum value with argmax()
x1.argmax()

tensor(9)

In [ ]:
# Find the value for the 9th position of the tensor
x1[9]

tensor(91)

## Reshaping stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimension permuted (swapped) in a certain way

In [ ]:
# Create a tensor
import torch
x2 = torch.arange(1., 10.)
x2, x2.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x2.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Add an extra dimension - example 2
x_reshaped2 = x2.reshape(9, 1)
x_reshaped2, x_reshaped2.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# Change the view
z = x2.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changez x (because a view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x2

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x2, x2, x2, x2], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# Using torch.squeeze()
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch.squeeze() -> removes all single dimensions from a target tensor
print(f"Previous Tensor: {x_reshaped}")
print(f"Previous Shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
print(f"\nNew Tensor: {x_squeezed}")
print(f"New Shape: {x_squeezed.shape}")

Previous Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape: torch.Size([1, 9])

New Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New Shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() -> adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous Tensor: {x_squeezed}")
print(f"Previous Shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape: {x_unsqueezed.shape}")

Previous Tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape: torch.Size([9])

New Tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Shape: torch.Size([1, 9])


In [ ]:
# torch.permute() -> rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0 to 1, axis 1 to 2, axis 2 to 0

print(f"Previous Shape: {x_original.shape}") # [height, width, colour_channels]
print(f"New Shape: {x_permuted.shape}") # [colour_channels, height, width]


Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing data with NumPy.

In [ ]:
# Import Torch
import torch

# Create a Tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket of our new tensor (dimension 1: dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0, 0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]


tensor(1)

In [ ]:
# Test Example: Display number 6 from the above example

x[0][1][2]

tensor(6)

In [ ]:
# Test Example 2: Display number 8 from the above example

x[0][2][1]

tensor(8)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, :, :]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
print('Return 9: ', x[0, 2, 2])

# Index on x to return 3, 6, 9
print('Return 3, 6, 9: ', x[:, :, 2])

Return 9:  tensor(9)
Return 3, 6, 9:  tensor([[3, 6, 9]])


## PyTorch Tensors & NumPy

NumPy is a popular scientific Python numerical computing library, and beacuse of this, PyTorch has the functionality to interact with it.

* Data in NumPy, but you want it in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Data PyTorch tensor, but you want it in NumPy -> `torch.Tensor.numpy()`

In [ ]:
# Import Torch & NumPy
import torch
import numpy as np

# Create a tensor
array = np.arange(1.0, 8.0)

# NumPy array to tensor
tensor = torch.from_numpy(array) # Warning - When converting from NumPy to Pytorch, PyTorch will reflect NumPy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Q: Change the value of array, what will this do to "tensor"? A: When the value of the array is changed, it does not change the value of the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array (Note: dtype changes from float64 to float32 which could lead to dtype errors)
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Q: Change the tensor, what happens to "numpy_tensor"? A: The numpy_tensor remains the same as they do not share memory.
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

The **random seed** concept is used to reduce the randomness in neural networks and PyTorch.

Essentially, what the random seed does is flavour the randomness.

Resource: https://pytorch.org/docs/stable/notes/randomness.html

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B  # comparisson operator "--" is used to compare the tensors

Tensor A:
tensor([[0.8968, 0.2582, 0.3079, 0.7189],
        [0.4341, 0.7081, 0.7513, 0.3273],
        [0.1663, 0.1136, 0.5636, 0.7088]])

Tensor B:
tensor([[0.3323, 0.6364, 0.4186, 0.7286],
        [0.1123, 0.1071, 0.2958, 0.4780],
        [0.0566, 0.1105, 0.1474, 0.8516]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
# Let's make some random but reproducable tensors

# Import torch and random
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs provide faster computation on numbers thanks to CUDA, NVIDEA hardware and PYTORCH working together behind the scenes.

**How to access a suitable GPU:**
1. Easy: Google Colab (Free or Paid Version both work)
2. Medium: Use your own GPU (Requires investment of purchasing GPU)
3. Hard: Cloud Computing such as AWS, GCP or AZURE (unlimited resources but expensive and complicated set up)

Note: for options 2 & 3, PyTorch + GPU drivers (CUDA) can take a litte bit of setting up, to do this, refer to PyTorch for up to date set up documentation.

**Resources:**
- https://pytorch.org/get-started/locally/
- https://pytorch.org/docs/stable/notes/cuda.html (**Device Agnostic Code** - It's best practise to set up device agnostic code so the code can run on GPU when available else CPU)


**Change from CPU to GPU in Google Collab:**
- Click Runtime
- Click Change Runtime Type
- Select GPU
- Restart Runtime
- `!nvidia-smi` to check GPU

In [ ]:
!nvidia-smi

Thu Feb 29 13:00:07 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### Check for GPU access with PyTorch

In [ ]:
# Change for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code (This allows you to run a GPU when available but still work on CPU if not available)
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors (and models) on the GPU

The reason we want our tensors / models on the GPU is beacause it results in faster computations than a CPU.

In [ ]:
# Create a tensor (default is on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the CPU



In [ ]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy error, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

AttributeError: 'numpy.ndarray' object has no attribute 'cpu'

In [ ]:
# The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU
tensor_on_gpu

array([2, 3, 4])

## Excercises and Extra-Curriculum

https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb

**Resources:**
- https://github.com/mrdbourke/pytorch-deep-learning/blob/main/00_pytorch_fundamentals.ipynb
- https://pytorch.org/tutorials/beginner/basics/intro.html
- https://pytorch.org/docs/stable/tensors.html#torch-tensor
- https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics
- https://youtu.be/f5liqUk0ZTw (How a Tensor Can Represent Data Video)



---




In [ ]:
# 1. Create a random tensor with shape (7, 7)

# Import torch
import torch

# Create random tensor
tensor1 = torch.rand(7, 7)
print(f"""Tensor 1 Values:
{tensor1}

Tensor 1 Shape:
{tensor1.shape}""")

Tensor 1 Values:
tensor([[0.2143, 0.2394, 0.7524, 0.7990, 0.6225, 0.5436, 0.5129],
        [0.1931, 0.3651, 0.2121, 0.2515, 0.4096, 0.3747, 0.5322],
        [0.6457, 0.9742, 0.7431, 0.5773, 0.2570, 0.1147, 0.6980],
        [0.5088, 0.5127, 0.0955, 0.3479, 0.8374, 0.0383, 0.4788],
        [0.1208, 0.2192, 0.3998, 0.5656, 0.8652, 0.4840, 0.5387],
        [0.8443, 0.1051, 0.6247, 0.9829, 0.2974, 0.1257, 0.9162],
        [0.6550, 0.5051, 0.5474, 0.7604, 0.9998, 0.7231, 0.9086]])
      
Tensor 1 Shape:
torch.Size([7, 7])


In [ ]:
# 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

# Create another random tensor
tensor2 = torch.rand(1, 7)
print(f"""Tensor 2 Values:
{tensor2}

Tensor 2 Shape:
{tensor2.shape}""")

# Perform matrix multiplication
tensor3 = torch.matmul(tensor1, tensor2.T)
print(f"""\nTensor 3 Values:
{tensor3}

Tensor 3 Shape:
{tensor3.shape}""")

Tensor 2 Values:
tensor([[0.4677, 0.4069, 0.7382, 0.9033, 0.4895, 0.4389, 0.9729]])
      
Tensor 2 Shape:
torch.Size([1, 7])

Tensor 3 Values:
tensor([[2.5170],
        [1.5054],
        [2.6236],
        [1.7239],
        [2.1117],
        [2.8787],
        [3.2935]])
      
Tensor 3 Shape:
torch.Size([7, 1])


In [ ]:
# 3. Set the random seed to 0 and do 2 & 3 over again.

# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED)

# Create two random tensors
randTensor1 = torch.rand(3, 4)
randTensor2 = torch.rand(4, 1)

# Matrix multiply tensors
randTensor3 = torch.matmul(randTensor1, randTensor2)
print(f"Result: {randTensor3.T}")


Result: tensor([[0.2353, 0.7228, 0.4278]])


In [ ]:
# 4. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one) - If there is, set the GPU random seed to 1234.

# Set random seed on the GPU
torch.cuda.manual_seed(1234)
gpu_seed = torch.cuda.initial_seed()

# Print GPU seed
print("GPU Seed:", gpu_seed)

GPU Seed: 1234


In [ ]:
# 5. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Create two random tensors on GPU
tensor_A = torch.rand((2, 3), device=device)
tensor_B = torch.rand((2, 3), device=device)

# Print device
print("Device:", device)

# Print tensors
print(f"Tensor A: {tensor_A}")
print(f"Tensor B: {tensor_B}")

Device: cuda
Tensor A: tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
Tensor B: tensor([[0.6208, 0.0276, 0.3255],
        [0.1114, 0.6812, 0.3608]], device='cuda:0')


In [ ]:
# 6. Perform a matrix multiplication on the tensors you created in step 5 (again, you may have to adjust the shapes of one of the tensors).

# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_A, tensor_B.T)
print(f"""Result Tensor Value:
{result}

Result Tensor Shape:
{result.shape}""")

Result Tensor Value:
tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

Result Tensor Shape:
torch.Size([2, 2])


In [ ]:
# 7. Find the maximum and minimum values of the output of 7.

# Find max
max_val = torch.max(result)
print(f"""Maximum Value:
{max_val}""")

# Find min
min_val = torch.min(result)
print(f"""
Minimum Value:
{min_val}""")

Maximum Value:
0.7667766809463501

Minimum Value:
0.27863210439682007


In [ ]:
# 8. Find the maximum and minimum index values of the output of 7.

# Find arg max
max_idx = torch.argmax(result)
print(f"""
Maximum Index Value:
{max_idx}""")


# Find arg min
min_idx = torch.argmin(result)
print(f"""
Minimum Index Value:
{min_idx}""")



Maximum Index Value:
1

Minimum Index Value:
0


In [ ]:
# 9. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_10D = torch.rand((1, 1, 1, 10))

# Remove single dimensions
tensor_1D = torch.squeeze(tensor_10D)

# Print out tensors and their shapes
print("Original Tensor:")
print(f"Value: {tensor_10D}")
print(f"Shape: {tensor_10D.shape}")

print("\nTensor with Single Dimensions Removed:")
print(f"Value: {tensor_1D}")
print(f"Shape: {tensor_1D.shape}")

Original Tensor:
Value: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Shape: torch.Size([1, 1, 1, 10])

Tensor with Single Dimensions Removed:
Value: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
Shape: torch.Size([10])
